# SPDX-FileCopyrightText: 2026 Gundu Labs
# SPDX-License-Identifier: GPL-3.0-or-later

[workspace]
members = [
    "gaze",
    "gaze-cli",
    "gaze-core",
    "gaze-vision",
    "pam-gaze",
    "pam-gaze-grosshack",
    "gaze-gui",
]
default-members = [
    "gaze",
    "gaze-cli",
    "gaze-core",
    "gaze-vision",
    "pam-gaze",
    "pam-gaze-grosshack",
    "gaze-gui",
]
resolver = "3"

[workspace.package]
categories = ["authentication"]
homepage = "https://gaze.gundulabs.com"
keywords = ["authentication", "biometrics", "face-recognition", "linux", "pam"]
license = "GPL-3.0-or-later"
publish = false
readme = "README.md"
repository = "https://github.com/GunduLabs/gaze"
