# SPDX-FileCopyrightText: 2026 Gundu Labs
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "gaze-gui"
version = "0.2.13"
edition = "2024"
description = "GTK application for configuring and enrolling users with Gaze"
categories.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true

[features]
default = []
openvino = ["gaze-core/openvino-config"]

[[bin]]
name = "gaze-gui"
path = "src/main.rs"

[dependencies]
gaze-core = { path = "../gaze-core", default-features = false }
gtk4 = { version = "0.11.4", features = ["gnome_46"] }
libadwaita = { version = "0.9.2", features = ["v1_4"] }
zbus = "5.19.0"
zbus_polkit = "5.1.0"
enumflags2 = "0.7.12"
anyhow = "1.0.104"
opencv = { version = "0.100.1", default-features = false, features = ["imgproc"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
futures = "0.3.34"
tokio = { version = "1.53.1", features = ["macros", "rt", "sync"] }
glib = { version = "0.22.9", features = ["v2_66"] }
