# SPDX-FileCopyrightText: 2026 Gundu Labs
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "gaze"
version = "0.2.12"
edition = "2024"
description = "Linux facial authentication daemon and machine-learning pipeline for Gaze"
categories.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true

[features]
default = []
openvino = ["gaze-core/openvino", "ort/openvino"]

[dependencies]
aes-gcm = "0.11.1"
anyhow = "1.0.104"
gaze-core = { path = "../gaze-core" }
getrandom = "0.4.3"
image = { version = "0.25.10", default-features = false, features = ["jpeg"] }
libc = "0.2.189"
nalgebra = "0.35.0"
ndarray = "0.17.2"
opencv = { version = "0.100.1", default-features = false, features = ["imgproc"] }
ort = { version = "2.0.0-rc.13", default-features = false, features = [
    "std",
    "ndarray",
    "tracing",
    "copy-dylibs",
    "api-24",
] }
sha2 = "0.11"
tokio = { version = "1.53.1", features = ["full", "rt-multi-thread"] }
ureq = "3.4.0"
uuid = { version = "1.25.0", features = ["v4"] }
zbus = "5.19.0"
zip = "8.6"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
futures = "0.3.34"
zbus_polkit = "5.0.0"
tss-esapi = "7.7.0"

[[bin]]
name = "gazed"
path = "src/main.rs"
